CONFIG_GPIO=y
CONFIG_LOG=y

# console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_BLINK_SLEEP_PERIOD_1000MS=y
CONFIG_ADVANCED_LED_SETTINGS=n
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_DURATION=500
